# Generated by Django 3.0.3 on 2020-10-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoadDataProces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(blank=True, max_length=100, null=True)),
                ('patinte_id', models.CharField(blank=True, max_length=100, null=True)),
                ('patiente_age', models.CharField(blank=True, max_length=100, null=True)),
                ('analysis_date', models.CharField(blank=True, max_length=100, null=True)),
                ('doctorName', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'LoadDataProces',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('patinte_id', models.CharField(blank=True, max_length=100, null=True)),
                ('patiente_age', models.CharField(blank=True, max_length=100, null=True)),
                ('analysis_date', models.CharField(blank=True, max_length=100, null=True)),
                ('prediction', models.CharField(blank=True, max_length=100, null=True)),
                ('eeg', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Prediction',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('mail', models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
