# Generated by Django 3.0.3 on 2020-10-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loaddataproces',
            old_name='doctorName',
            new_name='prediction',
        ),
        migrations.AddField(
            model_name='loaddataproces',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
