# Generated by Django 3.0.3 on 2020-10-04 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20201004_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loaddataproces',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='prediction',
            options={'managed': False},
        ),
    ]
