# Generated by Django 3.0.3 on 2020-10-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_edf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edfName', models.CharField(blank=True, max_length=100, null=True)),
                ('count', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Plot',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='EDF',
        ),
    ]
